### ISSUE TITLE
Figure out how to do links, asides, and custom components in source data

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#265]
We're going to want to include stuff in our site (asides, notes, custom components, auto-rollers, etc) that are linked to the content but aren't _part_ of the SRD content.

Options I can think of include 
- making it all HTML tags and stripping those out of the API content
- providing another content property that includes extra features (`desc_rich:` or similar?) 
- providing the inserts as another object, and including some programmatic ways to insert them. (eg. insert at the 3rd instance of this word, or similar)...but this feels gross.

**Comment by calumbell** [comment]
With PR #422 merged to staging, I think we are good to close this issue as we now have a good idea of how to add custom UI components to our source data.

1) Figure out what kind of custom component we need (links, asides, etc.)

2) Decide a tag to include in our source data. For example, our cross-links look like `<spell:fireball>Fireball</spell>` and `<spell:fireball>Fireball</spell>`

2) Write a Vue component to create the UI component, using props extracted from the tags in markdown. Declare it as a global component by using the `.global.vue` file extension instead of `.vue`

3) Update the `MdViewer.vue` component, and write [an extension for Vue Showdown](https://vue-showdown.js.org/guide/#extensions-1) to replace tags in the data with your new component
