### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#273]
Items should have breadcrumbs that reflect their location within the site hierarchy.

The normal Vue solution for this is to use metadata, but this isn't available in Nuxt. My thinking is  around autogenerating some sort of global index file that maps names to routes, but haven't been able to dive in yet. 

There's probably something better, def open to any suggestion that's reasonably automated during the build or static generation based on the data or markdown files.

**Comment by denmch** [comment]
I have a solution that takes the current route path and dynamically generates breadcrumbs. I think this could work with some cleaner routes in a few places:

* `magicitems` should be `magic-items` and magicitem-list.vue` should be index.vue
* `monster-list.vue` and `spells-table.vue` should each be renamed to `index.vue`
* pages under Characters, like Alignment, etc., should be in  a `/characters/` path rather than `/sections/`

If those changes are okay, then this solution should work.

**Comment by augustjohnson** [comment]
From a pure naming/categorization point of view, this is great.  This deviates a bit from the structure of the API though, where blocks of text (i.e the alignment page) were under the catchall "sections".  I don't think that's an issue, just pointing it out.  @eepMoody I vote yes.

**Comment by eepMoody** [comment]
@denmch I think those should be fine.

And yeah, the website deviates from the API for readability purposes, and I'm totally cool with reworking the NUXT folder structure to better represent that.

**Comment by denmch** [comment]
The more I've played with this, the more little exceptions I'm finding, and I don't think it's the best solution. I may take another tack.

**Comment by calumbell** [comment]
With the recent updates to the website structure I reckon I have an idea about how I could make this work. If nobody else is currently working on this issue i'll make a start

**Comment by calumbell** [comment]
With PR #416 merged into staging, I think it is safe to call this issue solved! Would somebody with write access be able to mark this issue as closed?
