### ISSUE TITLE
Monsters are missing descriptions

### ISSUE THREAD

**Issue by michaeleconomy** [open5e/open5e#312]
https://open5e.com/monsters/axe-beak  should have a description.   Looks like this is missing from the data model, so i added that ticket first: https://github.com/open5e/open5e-api/issues/44

**Comment by eepMoody** [comment]
Ah, I see. It looks like short descriptions of some beasts from the
appendix were included! I never looked at that section in any detail to
check for it since they're missing elsewhere.

I can look at ways to add this unless you get to it first. (I'm traveling
for work this week, so I probably won't be jumping on it quickly)

**Comment by eepMoody** [comment]
I believe this one is closed now that axe-beak is updated! @michaeleconomy let me know if you had a broader intent behind it and we can update.

**Comment by michaeleconomy** [comment]
Nice!

Thanks guys.
