### ISSUE TITLE
Ordering in /monsters/?ordering=-challenge_rating

### ISSUE THREAD

**Issue by lena0989** [open5e/open5e#322]
Hey guys, 
I've been playing with your API, and have noticed that your ordering does not really seems to be the right one. First I get all the monster with the challenge rating = 9, then with 8 until 2, and then I get all the monsters with the challenge rating = 23! 
Could you please check if you really order correctly? not only by the first digit, but by the whole number. Thank you! :) And merry Christmas! :)

Kind rgrds, 
Lena

**Comment by eepMoody** [comment]
Nice catch! Yeah, it looks like it's being sorted alphabetically instead of numerically lol. I'll look into how to handle that in Django over the holiday break!

**Comment by lena0989** [comment]
Hi @eepMoody, are there any news regarding this issue? :)

**Comment by eepMoody** [comment]
@lena0989 I know this has been sitting for a while, but there is now a fix for this thanks to some new community involvement!

If you switch to the new `cr` field on that endpoint it provides the value as a number (0.25, 0.5, 1, 2) instead of as string ("1/4", "1/2", "1", "2") which was the root cause of everyone's sorting issues.
