### ISSUE TITLE
Adjust Prettier config to resolve style issues

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#410]
Currently, prettier is enforcing some styles that are hard to read and confusing.

Key examples identified in #404 by @calumbell:

- [Self closing tags](https://github.com/open5e/open5e/pull/404#discussion_r1237082442) for components that don't contain slot contents
- [Enforce strings and tags on separate lines](https://github.com/open5e/open5e/pull/404#discussion_r1237151991)
- [Classes in templates should be displayed one-per line](https://github.com/open5e/open5e/pull/404#discussion_r1237292268) when beyond a reasonable length, for readability. Especially crucial when using tailwind.
- [Angle brackets are all funky](https://github.com/open5e/open5e/pull/404#discussion_r1237304724) and this is being enforced by pretter/eslint

Please add additional ideas to comments if you spot something that could use a change.

**Comment by calumbell** [comment]
I am planning to have a go at solving this issue this week.

Took a brief look at what could be done to modify the Prettier config to help resolve these style issues, and the answer is not too much. Prettier is designed to be an opinionated formatted with minimal options for configuration.

This issue is probably best solved by updating the linter config so that it correctly identifies these the weird styles while still agreeing with how Prettier formats the code so that the two aren't fighting each other (ie. Prettier formats a line of code in a way that the Linter considers an error).
