### ISSUE TITLE
 Sorting Issue: Incorrect Order when Sorting Monsters by Size #399 

### ISSUE THREAD

**Issue by uribracha2611** [open5e/open5e#441]
**Issue:**
When attempting to sort monsters by size using the Open5E API, there is an inconsistency in the sorting order. Currently, when sorting in descending order, the first results include "Titanic" monsters, followed by "Tiny" monsters, which deviates from the expected sorting order.

**Steps to Reproduce:**
    Use the API endpoint for sorting monsters by size in descending order: [https://api.open5e.com/monsters/?ordering=-size](https://api.open5e.com/monsters/?ordering=-size)
    Observe that the first results include "Titanic" monsters, but instead of continuing in descending order, the subsequent monsters are "Tiny."

**Expected Behavior**:
When sorting monsters by size in descending order, the expected order should be from the largest size category ("Titanic") to the smallest size category ("Tiny") according to the standard D&D size classification.

Note:
If I'm using the API incorrectly, please clarify the correct usage. However, if this is indeed a bug, I am willing to try to solve it and submit a pull request.

Thank you for your assistance!

**Comment by calumbell** [comment]
Hi! It looks like this issue is a [duplicate](https://github.com/open5e/open5e-api/issues/399) and also appears in the `open5e-api` repo. As this an API / backend issue, and its twin has gotten a lot more traction, I am going to go ahead and mark this as closed.

Thanks for flagging! I am looking forward to this getting fixed. Should be a big help with sorting monster lists on the frontend.
