### ISSUE TITLE
Compact Statblock links open a blank page

### ISSUE THREAD

**Issue by jlamond01** [open5e/open5e#506]
Following the Compact Statblock link at the bottom of a monster page brings you to https://open5e.com/monsters/compact/<monster name> which is blank.  This feature used to work several month ago but doesnt any more.

**Comment by calumbell** [comment]
Hi, thanks for flagging this! If this feature broke in the last few months I think it might be due to something changing on the  [API](https://github.com/open5e/open5e-api) (which was updated about ~2 months), as the live website itself hasn't been updated in nearly a year.

I was able to recreate the bug as follow:
- Navigate to https://open5e.com/monsters/goblin
- Click the "Compact statblock: goblin" link at the bottom of the page. This takes you to https://open5e.com/monsters/compact/goblin
- Page doesn't load. Console reads an error code `TypeError: e.monster.reactions is null`. Which makes me think that that API fields the FE is indexing into might have changed.

However, I cannot reproduce these errors on our development (`staging`) branch, where the compact statblocks appear to function as intended. I believe that this issue has already been fixed (as of PR #468) but hasn't been pushed to the live site just yet. With this in mind, I will ahead and mark this issue as closed.

Thanks again for flagging this! If anything it is a reminder that the website is overdue a new release
