### ISSUE TITLE
Update v2 API to filter by sources in all contexts

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e#560]

**Comment by calumbell** [comment]
I think I might have landed on a solution to this problem while working on issue #547 - looks like the source selector got torpedoed on top-level pages because the property for source's UID changed from `slug` to `key`. A few tweaks to `composables/api.ts` and I think it is fixed on top-level pages.

Expect a PR soon (tm)

**Comment by calumbell** [comment]
It looks like this issue was resolved as a side effect to PR #562 on the `feature/v2-api` branch. Of the top of my head the two main contexts that we need to filter sources by are:

1) On top level pages (ie. `/monsters` or `/spells`) that contain lists to many different items from the API
2) On the `/search` route (resources from other sources are hidden behind a piece of UI)

In both of these contexts it looks like filtering by source is working as intended.

I am going to go ahead and mark this issue as resolved. If I am wrong, feel free to reopen!
